package ru.tsu_taskgraph.core_api.entity;

public enum ActionLogEventType {
    PROJECT_CREATED,
    PROJECT_UPDATED,
    MEMBER_INVITED,
    MEMBER_ROLE_CHANGED,
    MEMBER_REMOVED,
    TASK_CREATED,
    TASK_UPDATED,
    TASK_STATUS_CHANGED,
    TASK_ASSIGNED,
    TASK_UNASSIGNED,
    TASK_DELETED,
    TIME_LOGGED,
    EDGE_CREATED,
    EDGE_DELETED,
    GRAPH_MUTATED,
    SMART_RECOVERY_APPLIED,
    AI_SKELETON_GENERATED,
    AI_ENRICHMENT_COMPLETED,
    WIKI_PAGE_CREATED,
    WIKI_PAGE_UPDATED,
    BLUEPRINT_GENERATED,
    GITHUB_TASK_CLOSED
}
