spring:
  application:
    name: tsu-taskgraph-api

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/task-graph-bd}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true


springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /api/v1/swagger-ui.html
    # Включает сохранение JWT токена при перезагрузке страницы Swagger в браузере
    persistAuthorization: true

jwt:
  secret: ${JWT_SECRET:bXktc3VwZXItc2VjcmV0LWtleS10YXNrZ3JhcGgtMjAyNC1zZWN1cmU=}
  expiration:
    access: 900000     # 15 минут в миллисекундах
    refresh: 604800000 # 7 дней в миллисекундах

server:
  forward-headers-strategy: framework

